In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
from PIL import Image

In [3]:
img = Image.open("dogs.jpeg")

In [5]:
img.show()

In [8]:
imgArr = np.array(img)
imgArr

array([[[240, 240, 240],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[240, 240, 240],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[240, 240, 240],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       ...,

       [[252, 248, 249],
        [254, 250, 251],
        [255, 253, 254],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[247, 245, 246],
        [250, 248, 249],
        [255, 253, 254],
        ...,
        [255, 255, 255],
        [252, 252, 252],
        [244, 244, 244]],

       [[253, 251, 254],
        [253, 251, 254],
        [253, 251, 252],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]]

In [10]:
imgArr.shape

(185, 272, 3)

In [14]:
newArr = imgArr.reshape(-1,2)
newArr.shape

(75480, 2)

In [15]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(newArr)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [16]:
print (kmeans.labels_)
print (len(kmeans.labels_))

[1 1 1 ... 1 1 1]
75480


In [23]:
predictions = kmeans.predict(newArr)
predictions

array([1, 1, 1, ..., 1, 1, 1])

In [21]:
new_img = Image.fromarray(predictions, 'RGB')
new_img.save('kmeans_prediction.png')
new_img.show()

IndexError: tuple index out of range

In [18]:
kmeans.cluster_centers_

array([[ 23.49638969,  23.34024851],
       [246.39752877, 244.88227177],
       [168.3040466 , 171.58920907]])